source 'https://rubygems.org'

gem 'capistrano', github: 'capistrano/capistrano'
gem 'capistrano-bundler', github: 'capistrano/bundler'
gem 'capistrano-rvm', github: 'capistrano/rvm'
gem 'capistrano-rails', github: 'capistrano/rails'
